### ISSUE TITLE
Feature Request - Add option to no use debrid service

### ISSUE THREAD

**Issue by DamianArielLerner** [insomniachi/Totoro#22]
in my country there is no need to use a debrid service, why i have to use one with this application?

**Comment by DamianArielLerner** [comment]
:/ sorry i'm going to wait for an actual solution, thank you for the answer, this project have future!

**Comment by insomniachi** [comment]
Initial level changes for streaming torrents are in.
It takes some time to start streaming. If it's lagging, pause for some time for the download to get ahead. (maybe it's my download speed being slow, idk)

On settings there is torrenting section
![image](https://user-images.githubusercontent.com/6525704/227690374-8dc061ed-a809-41ba-bcd3-839ece4d9d60.png)
![image](https://user-images.githubusercontent.com/6525704/227690411-485a5797-00ac-476d-a57c-cc7366036fcf.png)

For nya you'll have to give a mirror that works for you.

**Comment by reddit-reaper** [comment]
Change your download server here https://premiumize.me/speedtest i recommend not using automatic, cloudflare, or direct add those tend to not play well with players. Personally digital ocean Toronto is my best server

**Comment by reddit-reaper** [comment]
Very

> Initial level changes for streaming torrents are in. It takes some time to start streaming. If it's lagging, pause for some time for the download to get ahead. (maybe it's my download speed being slow, idk)
> 
> On settings there is torrenting section ![image](https://user-images.githubusercontent.com/6525704/227690374-8dc061ed-a809-41ba-bcd3-839ece4d9d60.png) ![image](https://user-images.githubusercontent.com/6525704/227690411-485a5797-00ac-476d-a57c-cc7366036fcf.png)
> 
> For nya you'll have to give a mirror that works for you.

Change your download server here https://premiumize.me/speedtest i recommend not using automatic, cloudflare, or direct add those tend to not play well with players. Personally digital ocean Toronto is my best server

**Comment by insomniachi** [comment]
Added option to use VLC media player instead of windows media player.
VLC is better than WMP at streaming MKV files.

So if you're using torrents, use Vlc media player, otherwise use the default. (Vlc package is still in pre-release)
![image](https://user-images.githubusercontent.com/6525704/228911961-5c86b9d5-2614-4842-b529-bb445248d6bc.png)

Playing with debrid service works perfectly now.
If you don't have a debrid service, I'm downloading the torrent while streaming, so it might some time to start playing.
I've added, download information to know if something is happening.
![image](https://user-images.githubusercontent.com/6525704/228913208-c80054b2-0e90-4e39-aadd-cc3676c9f758.png)
Video will start playing after first section is downloaded. After this i didn't notice any buffering (unless you seek).

Download will go to. \AppData\Local\Totoro\Torrents
Contents of this folder will get cleared at startup. so, if you want to keep the downloaded files, you might want to move them somewhere else before starting.
