### ISSUE TITLE
Missing search bar and banner in `Discover` menu

### ISSUE THREAD

**Issue by bachig26** [insomniachi/Totoro#3]
I though this issue is an loading problem, nut noticed that it's consistent in the 2 or 3 builds.

I can access the search bar as it is not available and also want to ask if the auto change banners are removed?

### Screenshot
![Totoro WinUI_yP7p7N6wmM](https://user-images.githubusercontent.com/96393348/209854528-fb9bae16-fc91-4cdd-9791-d12f652e0258.jpg)

**Comment by insomniachi** [comment]
The banners were removed. Initially everything in this page was scrapped from AnimixPlay.
since AnimixPlay went down.
![image](https://user-images.githubusercontent.com/6525704/209907777-3846994a-209f-4d89-815e-a5c193d94417.png)
content will be from the provider selected, and not all providers have a banner. so, it was removed.
It might come back for some providers in the future.

Search can be added.

**Comment by insomniachi** [comment]
Added search.
